src/window.cpp
Removed `not` operator in if statement. This doesn't play nice on windows.
=> Small Fix for Windows

CMakeLists.txt, README.md, src/window.cpp
What I did:
* Added cmake support (including installer generation)
* Small fix where `QSettings` wasn't properly saving values (see [here](http://doc.qt.io/qt-5/qsettings.html#details)).
* Made `parallel_sort()` function check for how many concurrent threads the hardware supports and use that value, if it is valid, for the number of threads to use during sorting.  
Notes:
* Mac OS installer part of the cmakelists is incomplete as I don't have a mac to test on. What I added should work but may be incomplete.
=> CMake Support and Small Fixes for Windows

src/mesh.cpp
The move constructor of the Mesh class was copying both vectors because std::move wasn't being called inside the constructor.
=> Fix Mesh move constructor by explicit calling std::move for the vectors

CMakeLists.txt
Added properties to generated qrc source files to tell CMake autogen to skip these generated files.
Resolves #27.
=> Remove CMake Warnings

CMakeLists.txt, src/app.cpp, src/app.h, src/backdrop.cpp, src/backdrop.h, src/canvas.cpp, src/canvas.h, src/glmesh.cpp, src/glmesh.h, src/window.cpp, src/window.h
* Migrated all `QGL*` classes to their `QOpenGL*` variants (resolves #29). 
* `override` specification to re-implemented virtual methods. 
* `explicit` keywords to make classes non-converting.
=> Migrate to QOpenGL Classes

CMakeLists.txt
On elementary os (ubuntu based) it fails to compile without explicit setting compiler to use c++11.
Testet with g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
=> it fails to compile without the compiler gets -std=c++11

CMakeLists.txt, gl/gl.qrc, gl/mesh_wireframe.frag, src/canvas.cpp, src/canvas.h, src/window.cpp, src/window.h
I have added a "draw style" submenu under "view." This has two options, "shaded" and "wireframe."
Shaded is classic mode. Wireframe uses GL_LINE.
I also made a custom plain-white fragment shader for wireframe to avoid it looking nasty.
Sadly, I do not have access to Windows or Mac build environments, so I have only tested this on 64bit Linux.
Respectfully yours,
Martin
=> Wireframe Draw Mode

src/app.cpp, src/main.cpp
When opening fstl, the initial `rebuild_recent_files` (window.cpp, 75) fails because the QCoreApplication set functions (which are used to determine the location for persistent settings files) have not yet been set. The initial rebuild happens as part of `window(new Window())` in the initialization section of the app constructor, but the core application settings get set later in the app construction.
This pull moves those core application setting assignments to main.cpp so that any settings loaded as any part of the app will always know where they should read from.
=> Fix initial settings

src/canvas.cpp, src/canvas.h, src/window.cpp, src/window.h
Hi, according to #41 I implemented an option point in the `View` menu to invert the zooming direction.
Only down side, it is not yet persistent, as - as far as I can see - there isn't yet a mechanism for storing configuration.
=> implements an `Invert Zoom` option

gl/gl.qrc, gl/mesh_surfaceangle.frag, src/canvas.cpp, src/canvas.h, src/window.cpp, src/window.h
Adds a "Surface Angle" draw mode almost identical to that of the Github STL viewer's.
#48
Thanks,
Martin
=> added surfaceangle draw mode based on github stl viewer

CMakeLists.txt, README.md, src/canvas.cpp, src/loader.cpp, src/main.cpp, src/window.cpp
Hi Everyone,
This pull request addresses #63 (and changed version from 0.9.4 to 0.9.5-snapshot). With this new system, the next full release would be 0.9.5. I don't think this project has a standard for inter-release versioning, so this is just a suggestion/draft, and please feel free to let me know if you have other thoughts.
In addition, it transitions some references from mkeeter/fstl to fstl-app/fstl. It also changes the linux build instructions to reflect the qmake changes made in #62. Finally, it addresses a couple memory management issues Valgrind found.
I have only tested on 64bit linux qt5.15.2-1.
Thanks,
Martin
=> Versioning in app, other small changes

CMakeLists.txt, src/canvas.cpp, src/window.cpp
`QString::null`, `QWheelEvent::pos` and `QWheelEvent::delta` are deprecated.
=> Fix several Qt deprecation warnings

src/canvas.cpp, src/canvas.h, src/main.cpp, src/window.cpp, src/window.h
Addresses #77. Noteworthy facets of this change:
- 'Autoreload' is now always enabled. I assume that since it is a persistent setting, it makes sense to be able to configure it even if no model is loaded.
- `Canvas::view_perspective` and `::view_orthogonal` are now merged into a single function with the help of constants `Canvas::P_PERSPECTIVE` and `::P_ORTHOGRAPHIC`. I had to touch this code to avoid a perspective-warp animation while loading from persisted settings.
- Organization name is now 'fstl-app'. This should make it easier for users to find their configurations, since this repo is no longer under mkeeter.
- 'Orthogonal'/'Orthographic' name split unified under 'Orthographic'.
Here is an example configuration file:
```
[General]
autoreload=false
drawAxes=true
drawMode=2 …
```
=> Remember application settings

src/window.cpp, src/window.h
This implements both a compact view (hiding the menu bar) and a fullscreen mode.
Fixes https://github.com/fstl-app/fstl/issues/80
=> Implement compact and fullscreen view

src/window.cpp
On windows using the regex *.[sS][tT][lL] did not work and neither did QFileDialog::HideNameFilterDetails. Removing the comma, however, did.
Fixes #73
Fixes #86
=> Fix STL file selection filter

src/canvas.cpp, src/canvas.h
The yaw/tilt object orientation is sometimes difficult to use for example if you want to rotate along the Y axis.
I have replaced it by a simple arcball mechanism that allow easier and more "natural" object orientation.
=> Add arc-ball mechanism to mouse control

src/canvas.cpp, src/canvas.h, src/window.cpp, src/window.h
Add an option "Reset rotation on load" in the View menu. It is set by default.
If set, the behavior is the same as before, that is the rotation of the object is reset when a new file is loaded.
If unset, then the actual rotation will be kept when reading a new file. This can be useful when exploring a directory containing files with same orientation.
=> Add the option to reset or not the rotation when loading a new stl file.

src/window.cpp
fstl got issues when another tool rewrites the file while its beeing displayed.
fstl will reload too fast and does not display complete file.
ideally writing tool writes a tmp file and replaces with the real file in an atomic operation.
=> wait to load the stl file until file size  does not change anymore

src/loader.cpp
Fixes #37.
It's the approach from #106 but using Qt only.
10 ms was still racy in my tests (writing STL from OpenSCAD), so I went with 100 ms.
=> Wait for the STL file size to stop changing.

src/window.cpp
This reverts commit c4dd685d128b1d940db328f78276a09672671df3.
With #107 merged, we no longer need this duplicate code in `window.cpp`
=> Revert "wait to load the stl file until file size  does not change anymore (#106)"

src/canvas.cpp, src/canvas.h, src/window.cpp, src/window.h
This adds three commits, making these changes:
1. Do not reset rotation on 'Center the model'. This used to also set the rotation to the 'Bottom' viewpoint, which is not always desirable. Now it only resets the scale, center and zoom to the default values.
2. Add shortcuts to Viewpoint submenu. The shortcuts are copied from PrusaSlicer, which is likely to be familiar to fstl users.
3. Add isometric view.
=> Add Viewpoint shortcuts and isometric view

CMakeLists.txt, src/app.cpp
- Minimum CMake version bumped to `3.5` to allow for building with CMake 4.x
- Fixed bug where files with Cyrillic symbols could not be opened when passed as CLI args (`fstl "тестовая модель.stl"`)
Fixes #122
=> fix: opening files with cyrillic symbols from command line

.clang-format, .github/workflows/linux.yml, CMakeLists.txt, src/app.cpp, src/app.h, src/axis.cpp, src/axis.h, src/backdrop.cpp, src/backdrop.h, src/canvas.cpp, src/canvas.h, src/glmesh.cpp, src/glmesh.h, src/loader.cpp, src/main.cpp, src/mesh.cpp, src/mesh.h, src/shaderlightprefs.cpp, src/shaderlightprefs.h, src/vertex.h, src/window.cpp, src/window.h
- Move to CMake `3.10` as minimum version. 
- Add `clang-format` file
- Add optional build targets for checking and fixing formatting using `clang-format`
- Added basic CI to build the project and check formatting on pushes and PRs
Closes #130
=> chore: update to cmake 3.10, enforce formatting with tooling
